#+TITLE: Doom Emacs Config
#+AUTHOR: Markus Mulvihill
#+DESCRIPTION: My emacs config setup
#+PROPERTY: header-args:emacs-lisp :tangle config.el

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

#+RESULTS:
* Configuring Emacs PATH
This is needed for Doom Emacs my path where GCC and G++ are installed

#+begin_src emacs-lisp
(setq exec-path (append exec-path '("C:\\msys64\\mingw64\\bin")))
(setenv "PATH" (concat "C:\\msys64\\mingw64\\bin;" (getenv "PATH")))
#+end_src

#+RESULTS:
: C:\msys64\mingw64\bin;C:\msys64\mingw64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Bitvise SSH Client;C:\Users\Markus Mulvihill\AppData\Local\Microsoft\WindowsApps;C:\intelFPGA_lite\20.1\modelsim_ase\win32aloem;C:\Users\Markus Mulvihill\AppData\Local\GitHubDesktop\bin;C:\Users\Markus Mulvihill\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Markus Mulvihill\.emacs.d\bin;C:\Users\Markus Mulvihill\emacs-29.2_1\bin;C:\Users\Markus Mulvihill\anaconda3\condabin;

* Adding Relative Lines
I included relative lines to be displayed on the left of the screen.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

* My Org Path
I use the default '~/org/' path to save all the my org files

#+begin_src emacs-lisp
(setq org-directory "~/org/")
 #+end_src

* Dracula Theme
 Here I am adding my a custom theme called Dracula, where i added the **dracula-theme.el** to a directory
 in '~/.emacs.d/'

 #+begin_src emacs-lisp
 (add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
 (load-theme 'dracula t)
 #+end_src

* Neotree
I will be using Neotree as a file structure navigation tool. It will act as a visual of your project layout

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/neotree")
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)
#+end_src

#+RESULTS:
: neotree-toggle

* Org-bullets
Instead of using the default Doom Emacs '*' for the markers, I will be adding in org-bullets instead.

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/org-bullets")
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

#+RESULTS:
| (lambda nil (org-bullets-mode 1)) | er/add-org-mode-expansions | +lookup--init-org-mode-handlers-h | (closure (t) (&rest _) (add-hook 'before-save-hook 'org-encrypt-entries nil t)) | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-fold-show-all append local] 5] | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | doom-disable-show-paren-mode-h | doom-disable-show-trailing-whitespace-h | +org-make-last-point-visible-h | evil-org-mode | org-eldoc-load | toc-org-enable | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | embrace-org-mode-hook |

 
* Adding bold and italic
 In this line I enabled bold and italics to appear in code and comments. This also
 includes the '/' and '*' to not appear around the work or comment.

 #+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword :slant italic))
#+end_src

* Development

** Language Servers
To begin using languages that do not have built in lsp into emacs we must enable lsp to enable emacs to communicate with the language server.

#+begin_src emacs-lisp
(use-package lsp-mode
:commands (lsp lsp-deferred)
:init
(setq lsp-keymap-prefix "C-c l") ;; Control l for lsp-mode
:config
(lsp-enable-which-key-integration t)) ;; descriptions for key bindings
#+end_src

#+RESULTS:

** Completion with Company Mode

#+begin_src emacs-lisp
(use-package company
  :after lsp-mode
  :hook (lsp-mode . company-mode)
  :bind (:map company-active-map
         ("<tab>" . company-complete-selection))
        (:map lsp-mode-map
         ("<tab>" . company-indent-or-complete-common))
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0))

(use-package company-box
  :hook (company-mode . company-box-mode))
#+end_src

#+RESULTS:
| evil-normalize-keymaps | company-mode-set-explicitly | company-box-mode |
